### ISSUE TITLE
Add support for automatically disabling scroll on body when a modal is open or something is fullscreen

### ISSUE THREAD

**Issue by haydn** [haydn/universal#2]
https://developer.mozilla.org/en-US/docs/Web/CSS/:modal

```css
body:has(dialog:modal) {
  overflow: hidden;
}
```
