### ISSUE TITLE
Support for `<dialog>`

### ISSUE THREAD

**Issue by haydn** [haydn/universal#3]
It probably makes sense to retain the default display values for dialogs:

```css
dialog {
  display: none;
}

dialog[open] {
  display: block;
}
```
